package cerror

const (
	BAD_REQUEST           = "BAD_REQUEST"
	UNAUTHORIZED          = "UNAUTHORIZED"
	FORBIDDEN             = "FORBIDDEN"
	NOT_FOUND             = "NOT_FOUND"
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
)

const (
	LINK_ALREADY_USE   = "LINK_ALREADY_USE"
	GENRES_NOT_FOUND   = "GENRES_NOT_FOUND"
	FORMAT_NOT_FOUND   = "FORMAT_NOT_FOUND"
	PERSONS_NOT_FOUND  = "PERSONS_NOT_FOUND"
	TEAM_NOT_MODERATED = "TEAM_NOT_MODERATED"
)
